name: LogIt
version: ${project.version}
authors: [LucasEasedUp, NorthPL]
main: io.github.lucaseasedup.logit.bukkit.LogItPlugin
softdepend: [AutoIn, Essentials, Multiverse-Core, ProtocolLib, Vault]

commands:
  logit:
    description: LogIt generic command.
    usage: /<command> [help|version|start|stop|reload|backup <force|restore <file <filename>|time <time>>|remove <amount>>|gotowr|globalpass|account <status <username>|info <username>|rename <username> <newUsername>|datum <username> <key>>|ipcount <ip>|config <get <path>|set <path> <value>|list [page]|reload>|convert|stats|import authme]

  login:
    description: Logs you in.
    usage: /<command> [password]
    aliases: [l]

  logout:
    description: Logs you out.
    usage: /<command>

  remember:
    description: Remembers your login.
    usage: /<command>

  register:
    description: Registers you.
    usage: /<command> <password> <confirmpassword>
    aliases: [reg]

  unregister:
    description: Unregisters you.
    usage: /<command> [password]

  changepass:
    description: Changes your password.
    usage: /<command> <oldpassword> <newpassword> <confirmpassword>

  changeemail:
    description: Changes your e-mail address.
    usage: /<command> <newemail>

  recoverpass:
    description: Recovers your password through e-mail.
    usage: /<command> <email>
  
  profile:
    description: Allows to view and edit player profiles.
    usage: /<command> <view [player]|edit [player]>
  
  acclock:
    description: Locks an account so that no one can log into it until it's unlocked.
    usage: /<command> <username>
  
  accunlock:
    description: Unlocks an account.
    usage: /<command> <username>
  
  loginhistory:
    descripton: Shows login history for your account.
    usage: /<command>
  
  $logit-nop-command:
    description: Reserved for internal use.
    usage: /<command>

permissions:
  logit.*:
    default: false
    children:
      logit.admin: true
  logit.player:
    default: not op
    children:
      logit: true
      logit.help: true
      logit.version: true
      logit.login.self: true
      logit.logout.self: true
      logit.remember: true
      logit.register.self: true
      logit.unregister.self: true
      logit.changepass.self: true
      logit.changeemail.self: true
      logit.recoverpass: true
      logit.profile.view.self: true
      logit.profile.view.others: true
      logit.profile.edit.self: true
      logit.loginhistory.self: true
  logit.mod:
    default: op
    children:
      logit.player: true
      logit.gotowr: true
      logit.account.status: true
      logit.account.info.*: true
      logit.login.others: true
      logit.logout.others: true
      logit.register.others: true
      logit.unregister.others: true
      logit.changepass.others: true
      logit.changeemail.others: true
      logit.profile.edit.others: true
      logit.loginhistory.others: true
  logit.admin:
    default: false
    children:
      logit.mod: true
      logit.start: true
      logit.stop: true
      logit.reload: true
      logit.backup.*: true
      logit.globalpass.*: true
      logit.account.rename: true
      logit.account.datum: true
      logit.ipcount: true
      logit.config.*: true
      logit.convert: true
      logit.stats: true
      logit.import: true
      logit.acclock: true
      logit.accunlock: true
  logit:
    default: true
  logit.help:
    default: true
  logit.version:
    default: true
  logit.start:
    default: false
  logit.stop:
    default: false
  logit.reload:
    default: false
  logit.backup.*:
    default: false
    children:
      logit.backup.force: true
      logit.backup.restore: true
      logit.backup.remove: true
  logit.backup.force:
    default: false
  logit.backup.restore:
    default: false
  logit.backup.remove:
    default: false
  logit.gotowr:
    default: false
  logit.globalpass.*:
    default: false
    children:
      logit.globalpass.generate: true
  logit.globalpass.generate:
    default: false
  logit.account.status:
    default: false
  logit.account.info.*:
    default: false
    children:
      logit.account.info: true
      logit.account.info.ip: true
      logit.account.info.email: true
      logit.account.info.lastactivedate: true
      logit.account.info.regdate: true
      logit.account.info.islocked: true
      logit.account.info.displayname: true
  logit.account.info:
    default: false
  logit.account.info.ip:
    default: false
  logit.account.info.email:
    default: false
  logit.account.info.lastactivedate:
    default: false
  logit.account.info.regdate:
    default: false
  logit.account.info.islocked:
    default: false
  logit.account.info.displayname:
    default: false
  logit.account.rename:
    default: false
  logit.account.datum:
    default: false
  logit.ipcount:
    default: false
  logit.config.*:
    default: false
    children:
      logit.config.get: true
      logit.config.set: true
      logit.config.list: true
      logit.config.reload: true
  logit.config.get:
    default: false
  logit.config.set:
    default: false
  logit.config.list:
    default: false
  logit.config.reload:
    default: false
  logit.convert:
    default: false
  logit.stats:
    default: false
  logit.import:
    default: false
  logit.login:
    default: false
    children:
      logit.login.self: true
  logit.login.self:
    default: false
  logit.login.others:
    default: false
  logit.logout:
    default: false
    children:
      logit.logout.self: true
  logit.logout.self:
    default: false
  logit.logout.others:
    default: false
  logit.remember:
    default: false
  logit.register:
    default: false
    children:
      logit.register.self: true
  logit.register.self:
    default: false
  logit.register.others:
    default: false
  logit.unregister:
    default: false
    children:
      logit.unregister.self: true
  logit.unregister.self:
    default: false
  logit.unregister.others:
    default: false
  logit.changepass:
    default: false
    children:
      logit.changepass.self: true
  logit.changepass.self:
    default: false
  logit.changepass.others:
    default: false
  logit.changeemail:
    default: false
    children:
      logit.changeemail.self: true
  logit.changeemail.self:
    default: false
  logit.changeemail.others:
    default: false
  logit.recoverpass:
    default: false
  logit.profile.view:
    default: false
    children:
      logit.profile.view.self: true
  logit.profile.view.self:
    default: false
  logit.profile.view.others:
    default: false
  logit.profile.edit:
    default: false
    children:
      logit.profile.edit.self: true
  logit.profile.edit.self:
    default: false
  logit.profile.edit.others:
    default: false
  logit.acclock:
    default: false
  logit.accunlock:
    default: false
  logit.loginhistory:
    default: false
    children:
      logit.loginhistory.self: true
  logit.loginhistory.self:
    default: false
  logit.loginhistory.others:
    default: false
